// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZsCCQrBeBnySR3rQs-AXr8OI4i2rgiI',
    appId: '1:96212872871:web:93ace9d288e64722a87582',
    messagingSenderId: '96212872871',
    projectId: 'control-time-app-3ddc9',
    authDomain: 'control-time-app-3ddc9.firebaseapp.com',
    databaseURL: 'https://control-time-app-3ddc9-default-rtdb.firebaseio.com',
    storageBucket: 'control-time-app-3ddc9.appspot.com',
    measurementId: 'G-BNHMXPY622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5_7IjjR63aLTyoV4gzqS-bc2IE2SH6Q',
    appId: '1:96212872871:android:928c05ba2c7ce1a2a87582',
    messagingSenderId: '96212872871',
    projectId: 'control-time-app-3ddc9',
    databaseURL: 'https://control-time-app-3ddc9-default-rtdb.firebaseio.com',
    storageBucket: 'control-time-app-3ddc9.appspot.com',
  );
}
